services:
    traefik:
        image: sbilifedockeradmin/traefik:latest
        restart: always
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        command:
            - --api.insecure=true
            - --providers.docker=true
            - --providers.docker.constraints=Label(`project`,`product-analyst`)
            - --accesslog=true
            - --log.level=DEBUG
        ports:
            - 11900:80
            - 11901:8080
    qdrant:
        image: sbilifedockeradmin/qdrant:latest
        restart: always
        volumes:
            - ./.local/.qdrant:/qdrant/storage
    qdrant-gateway:
        image: sbilifedockeradmin/qdrant-gateway:latest
        environment:
            - VECTORISER_HTTP_PORT=80
            - VECTOR_REPO_HTTP_PORT=81
            - QDRANT_URL=http://qdrant:6333
            - COLLECTION_NAME=insurance_material
        restart: always
        labels:
            - project=product-analyst
            - traefik.http.routers.vectoriser.rule=PathPrefix(`/api/v1/vectors`)
            - traefik.http.routers.vectoriser.service=vectoriser
            - traefik.http.services.vectoriser.loadBalancer.server.url=http://qdrant-gateway
            - traefik.http.routers.vector-repo.rule=PathPrefix(`/api/v1/vectorised-data`)
            - traefik.http.routers.vector-repo.service=vector-repo
            - traefik.http.services.vector-repo.loadBalancer.server.url=http://qdrant-gateway:81
    sqlite-gateway:
        image: sbilifedockeradmin/sqlite-gateway:latest
        environment:
            - HTTP_PORT=80
            - DB_PATH=/var/lib/repo/entities.sqlite
        volumes:
            - .local/.sqlite:/var/lib/repo
        restart: always
        labels:
            - project=product-analyst
            - traefik.http.routers.id-name-entities.rule=PathPrefix(`/api/v1/id-name-entities`)
    ingest-flow:
        image: sbilifedockeradmin/productanalyst-ingest-flow:latest
        restart: always
        env_file: .local/ingest-flow.env
        labels:
            - project=product-analyst
            - traefik.http.routers.ingest-flow--ingest.rule=PathPrefix(`/api/v1/ingest-requests`)
            - traefik.http.routers.ingest-flow--materials.rule=PathPrefix(`/api/v1/material-list-requests`)
    query-flow:
        image: sbilifedockeradmin/productanalyst-query-flow:latest
        restart: always
        env_file: .local/query-flow.env
        labels:
            - project=product-analyst
            - traefik.http.routers.productanalyst-query-flow.rule=PathPrefix(`/api/v1/material-queries`)
    ingest-flow-ui:
        image: sbilifedockeradmin/ingest-ui:latest
        env_file: .local/ingest-flow-ui.env
        restart: always
        labels:
            - project=product-analyst
            - traefik.http.routers.prodan-ingest-flow-ui.rule=PathPrefix(`/ingest-ui`)
    query-flow-ui:
        image: sbilifedockeradmin/product-query-ui:latest
        env_file: .local/query-flow-ui.env
        restart: always
        labels:
            - project=product-analyst
            - traefik.http.routers.prodan-query-flow-ui.rule=PathPrefix(`/product-query-ui`)
